language: objective-c
osx_image: xcode10.1
xcode_workspace: TravisCIBlog.xcworkspace # path to your xcodeproj folder
xcode_scheme: TravisCIBlog
xcode_destination: platform=iOS Simulator,OS=12.1,name=iPhone X
before_install:
    - pod install
after_success:
    - gem install jazzy
    - make documentation
  on:
    branch: master
